name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        
    - name: Prepare for deployment
      run: |
        echo "Current directory: $(pwd)"
        echo "Preparing files for deployment..."
        
        # Make startup script executable
        chmod +x _startup.sh
        chmod +x startup.sh
        
        # Create a simple startup command file that Azure will recognize
        echo "#!/bin/bash" > run.sh
        echo "cd /home/site/wwwroot" >> run.sh
        echo "gunicorn --bind=0.0.0.0 --timeout 600 application:app" >> run.sh
        chmod +x run.sh
        
        # List all important files to verify they exist
        echo "Checking for critical files:"
        echo "application.py exists: $(test -f application.py && echo YES || echo NO)"
        echo "wsgi.py exists: $(test -f wsgi.py && echo YES || echo NO)"
        echo "backend/wsgi.py exists: $(test -f backend/wsgi.py && echo YES || echo NO)"
        echo "requirements.txt exists: $(test -f requirements.txt && echo YES || echo NO)"
        echo ".deployment exists: $(test -f .deployment && echo YES || echo NO)"
        echo "web.config exists: $(test -f web.config && echo YES || echo NO)"
        echo "handler.fcgi exists: $(test -f handler.fcgi && echo YES || echo NO)"
        echo "build directory exists: $(test -d build && echo YES || echo NO)"
        
        # Make handler.fcgi executable
        chmod +x handler.fcgi
        
        # Show the deployment files
        echo "Deployment files:"
        ls -la
        
    - name: Create deployment package
      run: |
        # Create a zip file with all necessary files
        zip -r deploy.zip . -x "*.git*" "node_modules/*" "venv/*"
        echo "Deployment package created"
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Note: Make sure AZURE_CREDENTIALS secret is set in GitHub repository settings
      # Format should be: {"clientId":"<client-id>","clientSecret":"<client-secret>","subscriptionId":"<subscription-id>","tenantId":"<tenant-id>"}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AIhome' # Updated to the new App Service name
        slot-name: 'production'
        package: ./deploy.zip
