name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Prepare for deployment
      run: |
        echo "Current directory: $(pwd)"
        echo "Preparing files for deployment..."
        
        # Make startup script executable
        chmod +x _startup.sh
        
        # Create a simple startup command file that Azure will recognize
        echo "gunicorn --bind=0.0.0.0:8000 wsgi:app" > startup.sh
        chmod +x startup.sh
        
        # Show the deployment files
        echo "Deployment files:"
        ls -la
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rts-search-app'
        slot-name: 'production'
        package: .
